name: Feature Request
description: Suggest an idea for Entry Type Fields
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in Entry Type Fields, and why?
    validations:
      required: true
