name: Question
description: Ask a question about Entry Type Fields
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: What question would you like to ask?
    validations:
      required: true
